### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [wuxx/AntRunner#1]
Hello!

I found this project from https://hackaday.com/2022/09/17/antrunner-is-the-satellite-antenna-mount-you-need-to-take-with-you/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and images in any purpose?
It would be great to see any popular open source license.

**Comment by wuxx** [comment]
Hello, I will add the license later, and more documents will commit, please wait.

**Comment by vazhnov** [comment]
GPL-3.0 license — great! Thank you!
