### ISSUE TITLE
Provide Grbl ESP32 build configuration?

### ISSUE THREAD

**Issue by natevw** [wuxx/AntRunner#4]
The default settings of the controller can be accessed from serial and also are copied into: <https://github.com/Hamlib/Hamlib/blob/e9fb733dae0e7acb2897850787ebbdcf2520e37c/rotators/grbltrk/grbltrk.c#L55-L93> And some version info can be requested over serial with`$I` command.

But can you provide compile-time settings for Machine configuration headers, how to build firmware bin provided here?

**Comment by wuxx** [comment]
hello, already commit the source code 
https://github.com/wuxx/AntRunner/blob/master/software/Grbl_Esp32-master.zip

**Comment by natevw** [comment]
Okay, yes I see now! 👍
