### ISSUE TITLE
Other board/card

### ISSUE THREAD

**Issue by TREBOR81400** [wuxx/AntRunner#7]
Hello, is it possible to run the AntRunner program on a “MakerFR Grbl 32Bits Board” card, Thank you

**Comment by wuxx** [comment]
Hello, board based on ESP32 should be ok

**Comment by TREBOR81400** [comment]
thanks I will try.......

**Comment by TREBOR81400** [comment]
Hello
I tried to compile AnrRunner on a GRBL 32bits board V2 from MakerFr, the map manager version 1.0.4 does not recognize it, I tried to compile with the latest version, there the card is taken into account but I have an error message like this:
error: cannot convert 'esp_interface_t' to 'wifi_interface_t'
Do you have an idea to compile on my map?
Thank you
