### ISSUE TITLE
AntRunner Start Wifi.bat

### ISSUE THREAD

**Issue by TREBOR81400** [wuxx/AntRunner#9]
hello, could you give me the exact syntax for the "AntRunner Start Wifi.bat" Thank you

**Comment by wuxx** [comment]
Hello, this is a dos bat script. You can use a text editor (notepad++ is recommended) to open this bat script for editing. There is only one command in it. Generally, you only need to modify the port number in jthis bat file.

**Comment by TREBOR81400** [comment]
Hello, the script for serial is:
.\bin\rotctld.exe -vvvvv -m 2401 -r COMXpause
What is the good script for Wifi, please
Thank you
    Le dimanche 1 octobre 2023 à 03:34:42 UTC+2, wuxx ***@***.***> a écrit :  
 
 


Hello, this is a dos bat script. You can use a text editor (notepad++ is recommended) to open this bat script for editing. There is only one command in it. Generally, you only need to modify the port number in jthis bat file.

**Comment by wuxx** [comment]
Control based on wifi is currently not supported because wifi may be unstable. It is currently recommended to use a wired serial port for control.

**Comment by TREBOR81400** [comment]
Ok Thank You
    Le mardi 3 octobre 2023 à 03:30:32 UTC+2, wuxx ***@***.***> a écrit :  
 
 


Control based on wifi is currently not supported because wifi may be unstable. It is currently recommended to use a wired serial port for control.
